apiVersion: apps/v1
kind: Deployment

metadata:
  name: simple-sre-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: simple-sre-api

  template:
    metadata:
      labels:
        app: simple-sre-api

    spec:
      containers:
        - name: api
          image: simple-sre-api:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 10
